/** Micro-copy inside the illustrated cards — labels, readouts and chips. */

const pt = {
  baas: {
    account: 'Conta digital',
    active: 'ativa',
    ledger: 'LEDGER',
    ledgerValue: 'D+0',
    iso: 'ISO 20022',
    isoValue: '19 msgs',
  },
  dashboard: {
    title: 'Visão geral',
    badge: 'TEMPO REAL',
    balanceLabel: 'SALDO CONSOLIDADO',
    balanceValue: 'R$ 48,2M',
    reconLabel: 'CONCILIAÇÃO',
    reconValue: '100%',
    rows: [
      ['pix · entradas', '12.480'],
      ['cartão · autorizações', '3.907'],
      ['pendências operacionais', '0'],
    ],
  },
  rails: {
    chips: ['PIX', 'TED', 'BOLETO', 'CARTÃO', 'QR CODE', 'COMPE', 'RECORRÊNCIA'],
    splitTitle: 'SPLIT DE PAGAMENTO',
    splitParts: ['lojista 60%', 'plataforma 30%', 'taxa 10%'],
  },
  cards: {
    virtual: 'VIRTUAL',
    number: '•••• •••• •••• 4821',
    holder: 'titular',
    kind: 'crédito · débito',
    activeLabel: 'cartões ativos',
    activeValue: '184.320',
    authLabel: 'autorização média',
    authValue: '38 ms',
  },
  investments: {
    title: 'Investimentos na conta',
    badge: 'integrado',
    rows: [
      ['CDB', '12,4% a.a.'],
      ['Tesouro', '10,8% a.a.'],
      ['Fundos', 'carteira própria'],
    ],
  },
  agreements: {
    a: 'Instituição A',
    b: 'Instituição B',
    ruleTitle: 'REGRA DO CONVÊNIO',
    ruleParts: ['repasse 70%', 'tarifa 20%', 'fundo 10%'],
    chips: ['conciliação D+0', 'limite por acordo'],
  },
  billing: {
    title: 'Cobranças',
    badge: 'PAINEL ÚNICO',
    rows: [
      ['boleto · 8421', 'pago'],
      ['carnê 12x · 3308', 'em aberto'],
      ['recorrência · 7712', 'agendada'],
    ],
  },
  security: {
    title: 'Transação avaliada',
    rows: [
      ['biometria', 'ok'],
      ['geolocalização', 'ok'],
      ['score antifraude', '0.98'],
      ['criptografia', 'AES-256'],
    ],
    trail: 'trilha de auditoria registrada',
  },
  antifraud: {
    title: 'Fila de análise',
    badge: 'tempo real',
    rows: [
      ['tx 9f21 · score 0.12', 'aprovada'],
      ['tx a3c8 · score 0.61', 'revisão'],
      ['tx b7d4 · score 0.94', 'bloqueada'],
    ],
    chips: ['PLD · KYC contínuo', 'reporte regulatório'],
  },
  regulatory: {
    title: 'Remessas regulatórias',
    badge: 'EM DIA',
    rows: [
      ['CADOC · BACEN', 'enviado'],
      ['COSIF · balancete', 'conciliado'],
      ['e-Financeira', 'agendado'],
      ['FGC', 'integrado'],
    ],
    chips: ['Bloqueio Judicial', 'SIMBA', 'BC Correios'],
  },
  sandbox: {
    title: 'Ambiente sandbox',
    badge: 'GRATUITO',
    code: [
      'curl -X POST /sandbox/v1/accounts',
      '  -H "Authorization: Bearer test_key"',
      '201 created · env: sandbox',
    ],
    chips: ['sem cartão de crédito', 'dados fictícios'],
  },
  homeHero: {
    pixLabel: 'PIX RECEBIDO',
    pixBadge: 'D+0',
    pixValue: 'R$ 12.480,00',
    pixMeta: 'conta ····8421 · liquidado',
    cardVirtual: 'VIRTUAL',
    cardNumber: '•••• 4821',
    ledgerTitle: 'Ledger · tempo real',
    ledgerBadge: 'ONLINE',
    tpsLabel: 'TPS',
    tpsValue: '16,7K',
    latencyLabel: 'Latência p99',
    latencyValue: '42 ms',
    request: 'POST /v1/accounts',
    response: '201 created · account_id: cbx_8f21',
  },
  banksHero: {
    title: 'Operação do banco',
    badge: 'EM PRODUÇÃO',
    tiles: [
      ['D+0', 'liquidação no mesmo dia'],
      ['API', 'integração sem trocar o core'],
      ['7', 'rails de pagamento prontos'],
      ['99,99%', 'uptime contratado em SLA'],
    ],
  },
  phone: {
    time: '9:41',
    greeting: 'Boa tarde',
    balanceLabel: 'SALDO DISPONÍVEL',
    balanceValue: 'R$ 48.240,00',
    actions: ['Pix', 'Pagar', 'Cartão'],
    rows: [
      ['Pix recebido', '+ 1.240,00'],
      ['Cartão · débito', '− 89,90'],
      ['Investimento', '+ 312,45'],
    ],
  },
};

const en: typeof pt = {
  baas: {
    account: 'Digital account',
    active: 'active',
    ledger: 'LEDGER',
    ledgerValue: 'D+0',
    iso: 'ISO 20022',
    isoValue: '19 msgs',
  },
  dashboard: {
    title: 'Overview',
    badge: 'REAL TIME',
    balanceLabel: 'CONSOLIDATED BALANCE',
    balanceValue: 'R$ 48.2M',
    reconLabel: 'RECONCILIATION',
    reconValue: '100%',
    rows: [
      ['pix · inbound', '12,480'],
      ['card · authorisations', '3,907'],
      ['operational exceptions', '0'],
    ],
  },
  rails: {
    chips: ['PIX', 'WIRE', 'BOLETO', 'CARD', 'QR CODE', 'COMPE', 'RECURRING'],
    splitTitle: 'PAYMENT SPLIT',
    splitParts: ['merchant 60%', 'platform 30%', 'fee 10%'],
  },
  cards: {
    virtual: 'VIRTUAL',
    number: '•••• •••• •••• 4821',
    holder: 'holder',
    kind: 'credit · debit',
    activeLabel: 'active cards',
    activeValue: '184,320',
    authLabel: 'average authorisation',
    authValue: '38 ms',
  },
  investments: {
    title: 'Investments in the account',
    badge: 'integrated',
    rows: [
      ['CDB', '12.4% p.a.'],
      ['Treasury', '10.8% p.a.'],
      ['Funds', 'own portfolio'],
    ],
  },
  agreements: {
    a: 'Institution A',
    b: 'Institution B',
    ruleTitle: 'AGREEMENT RULE',
    ruleParts: ['transfer 70%', 'fee 20%', 'fund 10%'],
    chips: ['D+0 reconciliation', 'limit per agreement'],
  },
  billing: {
    title: 'Billing',
    badge: 'SINGLE PANEL',
    rows: [
      ['boleto · 8421', 'paid'],
      ['payment book 12x · 3308', 'open'],
      ['recurring · 7712', 'scheduled'],
    ],
  },
  security: {
    title: 'Transaction assessed',
    rows: [
      ['biometrics', 'ok'],
      ['geolocation', 'ok'],
      ['anti-fraud score', '0.98'],
      ['encryption', 'AES-256'],
    ],
    trail: 'audit trail recorded',
  },
  antifraud: {
    title: 'Review queue',
    badge: 'real time',
    rows: [
      ['tx 9f21 · score 0.12', 'approved'],
      ['tx a3c8 · score 0.61', 'review'],
      ['tx b7d4 · score 0.94', 'blocked'],
    ],
    chips: ['AML · continuous KYC', 'regulatory report'],
  },
  regulatory: {
    title: 'Regulatory filings',
    badge: 'UP TO DATE',
    rows: [
      ['CADOC · Central Bank', 'filed'],
      ['COSIF · trial balance', 'reconciled'],
      ['e-Financeira', 'scheduled'],
      ['FGC', 'integrated'],
    ],
    chips: ['Judicial blocking', 'SIMBA', 'BC Correios'],
  },
  sandbox: {
    title: 'Sandbox environment',
    badge: 'FREE',
    code: [
      'curl -X POST /sandbox/v1/accounts',
      '  -H "Authorization: Bearer test_key"',
      '201 created · env: sandbox',
    ],
    chips: ['no credit card', 'fictitious data'],
  },
  homeHero: {
    pixLabel: 'PIX RECEIVED',
    pixBadge: 'D+0',
    pixValue: 'R$ 12,480.00',
    pixMeta: 'account ····8421 · settled',
    cardVirtual: 'VIRTUAL',
    cardNumber: '•••• 4821',
    ledgerTitle: 'Ledger · real time',
    ledgerBadge: 'ONLINE',
    tpsLabel: 'TPS',
    tpsValue: '16.7K',
    latencyLabel: 'p99 latency',
    latencyValue: '42 ms',
    request: 'POST /v1/accounts',
    response: '201 created · account_id: cbx_8f21',
  },
  banksHero: {
    title: "The bank's operation",
    badge: 'IN PRODUCTION',
    tiles: [
      ['D+0', 'same-day settlement'],
      ['API', 'integration without replacing the core'],
      ['7', 'payment rails ready to use'],
      ['99.99%', 'uptime committed in the SLA'],
    ],
  },
  phone: {
    time: '9:41',
    greeting: 'Good afternoon',
    balanceLabel: 'AVAILABLE BALANCE',
    balanceValue: 'R$ 48,240.00',
    actions: ['Pix', 'Pay', 'Card'],
    rows: [
      ['Pix received', '+ 1,240.00'],
      ['Card · debit', '− 89.90'],
      ['Investment', '+ 312.45'],
    ],
  },
};

const es: typeof pt = {
  baas: {
    account: 'Cuenta digital',
    active: 'activa',
    ledger: 'LEDGER',
    ledgerValue: 'D+0',
    iso: 'ISO 20022',
    isoValue: '19 msgs',
  },
  dashboard: {
    title: 'Visión general',
    badge: 'TIEMPO REAL',
    balanceLabel: 'SALDO CONSOLIDADO',
    balanceValue: 'R$ 48,2M',
    reconLabel: 'CONCILIACIÓN',
    reconValue: '100%',
    rows: [
      ['pix · entradas', '12.480'],
      ['tarjeta · autorizaciones', '3.907'],
      ['pendientes operativos', '0'],
    ],
  },
  rails: {
    chips: ['PIX', 'TRANSFERENCIA', 'BOLETO', 'TARJETA', 'QR CODE', 'COMPE', 'RECURRENCIA'],
    splitTitle: 'SPLIT DE PAGO',
    splitParts: ['comercio 60%', 'plataforma 30%', 'tarifa 10%'],
  },
  cards: {
    virtual: 'VIRTUAL',
    number: '•••• •••• •••• 4821',
    holder: 'titular',
    kind: 'crédito · débito',
    activeLabel: 'tarjetas activas',
    activeValue: '184.320',
    authLabel: 'autorización promedio',
    authValue: '38 ms',
  },
  investments: {
    title: 'Inversiones en la cuenta',
    badge: 'integrado',
    rows: [
      ['CDB', '12,4% anual'],
      ['Tesoro', '10,8% anual'],
      ['Fondos', 'cartera propia'],
    ],
  },
  agreements: {
    a: 'Institución A',
    b: 'Institución B',
    ruleTitle: 'REGLA DEL CONVENIO',
    ruleParts: ['traspaso 70%', 'tarifa 20%', 'fondo 10%'],
    chips: ['conciliación D+0', 'límite por acuerdo'],
  },
  billing: {
    title: 'Cobranzas',
    badge: 'PANEL ÚNICO',
    rows: [
      ['boleto · 8421', 'pagado'],
      ['plan 12x · 3308', 'abierto'],
      ['recurrencia · 7712', 'agendada'],
    ],
  },
  security: {
    title: 'Transacción evaluada',
    rows: [
      ['biometría', 'ok'],
      ['geolocalización', 'ok'],
      ['score antifraude', '0.98'],
      ['cifrado', 'AES-256'],
    ],
    trail: 'traza de auditoría registrada',
  },
  antifraud: {
    title: 'Fila de análisis',
    badge: 'tiempo real',
    rows: [
      ['tx 9f21 · score 0.12', 'aprobada'],
      ['tx a3c8 · score 0.61', 'revisión'],
      ['tx b7d4 · score 0.94', 'bloqueada'],
    ],
    chips: ['PLD · KYC continuo', 'reporte regulatorio'],
  },
  regulatory: {
    title: 'Envíos regulatorios',
    badge: 'AL DÍA',
    rows: [
      ['CADOC · BACEN', 'enviado'],
      ['COSIF · balance', 'conciliado'],
      ['e-Financeira', 'agendado'],
      ['FGC', 'integrado'],
    ],
    chips: ['Bloqueo Judicial', 'SIMBA', 'BC Correios'],
  },
  sandbox: {
    title: 'Ambiente sandbox',
    badge: 'GRATUITO',
    code: [
      'curl -X POST /sandbox/v1/accounts',
      '  -H "Authorization: Bearer test_key"',
      '201 created · env: sandbox',
    ],
    chips: ['sin tarjeta de crédito', 'datos ficticios'],
  },
  homeHero: {
    pixLabel: 'PIX RECIBIDO',
    pixBadge: 'D+0',
    pixValue: 'R$ 12.480,00',
    pixMeta: 'cuenta ····8421 · liquidado',
    cardVirtual: 'VIRTUAL',
    cardNumber: '•••• 4821',
    ledgerTitle: 'Ledger · tiempo real',
    ledgerBadge: 'ONLINE',
    tpsLabel: 'TPS',
    tpsValue: '16,7K',
    latencyLabel: 'Latencia p99',
    latencyValue: '42 ms',
    request: 'POST /v1/accounts',
    response: '201 created · account_id: cbx_8f21',
  },
  banksHero: {
    title: 'Operación del banco',
    badge: 'EN PRODUCCIÓN',
    tiles: [
      ['D+0', 'liquidación el mismo día'],
      ['API', 'integración sin cambiar el core'],
      ['7', 'rieles de pago listos'],
      ['99,99%', 'uptime contratado en SLA'],
    ],
  },
  phone: {
    time: '9:41',
    greeting: 'Buenas tardes',
    balanceLabel: 'SALDO DISPONIBLE',
    balanceValue: 'R$ 48.240,00',
    actions: ['Pix', 'Pagar', 'Tarjeta'],
    rows: [
      ['Pix recibido', '+ 1.240,00'],
      ['Tarjeta · débito', '− 89,90'],
      ['Inversión', '+ 312,45'],
    ],
  },
};

export const illustrations = { pt, en, es };
export type IllustrationCopy = typeof pt;
