/** Page-level copy for everything that isn't the home page or a product. */

const pt = {
  produtos: {
    eyebrow: 'Produtos e soluções',
    title: 'Uma infraestrutura, todas as soluções financeiras que seu negócio precisa',
    lead: 'Do core bancário à adquirência, cada camada funciona isolada ou integrada. Você escolhe por onde começar.',
    ctaTitle: 'Não sabe por onde começar?',
    ctaText:
      'Nosso time desenha o desenho técnico junto com o seu, a partir do que já existe na sua operação.',
  },
  bancos: {
    eyebrow: 'Soluções · Para bancos',
    title: 'Bancos que evoluem sem recomeçar do zero',
    lead: 'Conecte novos produtos ao core que já existe, no ritmo do seu roadmap e sob as regras do regulador.',
    contextEyebrow: 'Contexto de mercado',
    contextTitle: 'A pressão vem de fora, mas o gargalo é interno',
    context: [
      ['Novos entrantes, mesmas licenças', 'Fintechs lançam em semanas o que leva trimestres no banco.'],
      ['Legado difícil de mexer', 'Cada mudança no core carrega risco operacional alto.'],
      ['Exigência regulatória crescente', 'Reportes e controles consomem o time de tecnologia.'],
    ],
    beforeTitle: 'Antes e depois, na operação do banco',
    todayTitle: 'Hoje',
    today: [
      'Projetos de produto travados na fila do core',
      'Conciliação em planilhas entre fornecedores',
      'Cada novo rail exige um projeto próprio',
    ],
    withTitle: 'Com a Corebanx',
    with: [
      'Novos produtos publicados sobre o core atual',
      'Conciliação automática em um só extrato',
      'Rails novos ativados por configuração',
    ],
    useCasesEyebrow: 'Casos de uso',
    useCasesTitle: 'Por onde os bancos começam',
    tabs: [
      {
        label: 'Conta digital white label',
        title: 'Conta digital white label',
        text: 'Lance uma conta completa com a marca do banco, sem tocar no sistema legado.',
        checks: [
          'Onboarding digital com biometria',
          'App iOS e Android publicados na sua marca',
          'PIX, cartão e boleto desde o primeiro dia',
        ],
      },
      {
        label: 'Adquirência própria',
        title: 'Adquirência própria',
        text: 'Capture e liquide transações do seu próprio portfólio de lojistas.',
        checks: [
          'Maquininhas e gateway sob a sua bandeira',
          'Split e antecipação configuráveis',
          'Receita de adquirência dentro de casa',
        ],
      },
      {
        label: 'Modernização de rails',
        title: 'Modernização de rails',
        text: 'Troque integrações ponto a ponto por uma camada única de mensageria.',
        checks: [
          'Mensageria ISO 20022 padronizada',
          'Conciliação e reprocessamento automáticos',
          'Observabilidade fim a fim das transações',
        ],
      },
    ],
    volumeLabel: 'VOLUME CAPTURADO',
    isoMessages: [
      'pacs.008 · credit transfer',
      'pacs.002 · status report',
      'camt.054 · notification',
      'camt.053 · statement',
    ],
    trustTitle: 'Por que instituições reguladas escolhem a Corebanx',
    trust: [
      ['Regulatório', 'Processos e reportes desenhados para o ambiente supervisionado.'],
      ['Segurança', 'Criptografia, biometria e trilhas de auditoria por padrão.'],
      ['Escala', '16,7K TPS comprovados e uptime de 99,99% em SLA.'],
      ['Suporte', 'Time técnico dedicado da integração ao go-live.'],
    ],
    proofTitle: 'Instituições financeiras que operam com a Corebanx',
    proofLogo: 'logo instituição',
    ctaTitle: 'Fale com nosso time sobre sua operação',
    ctaText: 'Trazemos um especialista que já implantou infraestrutura em instituições reguladas.',
  },
  quemSomos: {
    eyebrow: 'Quem somos',
    title: 'Uma infratech construída por quem opera sistemas financeiros',
    lead: 'Nascemos para resolver o que trava a inovação dentro das instituições: a infraestrutura.',
    timelineEyebrow: 'Linha do tempo',
    timeline: [
      ['2021', 'Fundação', 'Início da Corebanx com foco em core bancário como serviço.'],
      ['2022', 'Primeiras integrações', 'Conta digital e PIX em produção com parceiros iniciais.'],
      ['2023', 'Camada de pagamentos', 'Unificação dos rails e lançamento do split de pagamento.'],
      ['2024', 'Adquirência e white label', 'Plataforma completa disponível sob a marca do parceiro.'],
      ['2025', 'Escala comprovada', '16,7K TPS e mensageria ISO 20022 em operação.'],
    ],
    missionEyebrow: 'Missão',
    missionTitle:
      'Tornar a infraestrutura financeira um detalhe resolvido para quem quer inovar.',
    values: [
      ['Solidez', 'Sistema no ar é o mínimo, não o diferencial.'],
      ['Clareza', 'Documentação e contratos sem letras miúdas.'],
      ['Parceria', 'O nosso time entra junto no projeto do cliente.'],
      ['Rigor', 'Segurança e regulatório antes de qualquer atalho.'],
    ],
    partnersEyebrow: 'Parceiros estratégicos',
    partnerLogo: 'logo parceiro',
    closingTitle: 'Conheça a plataforma ou fale com o nosso time.',
  },
  cases: {
    eyebrow: 'Cases e parceiros',
    title: 'Resultados construídos junto com nossos parceiros',
    logo: 'logo',
    cards: [
      ['Banco', 'Nome do cliente', 'Placeholder editável: resultado obtido em uma frase.'],
      ['Fintech', 'Nome do cliente', 'Placeholder editável: resultado obtido em uma frase.'],
      ['Subadquirente', 'Nome do cliente', 'Placeholder editável: resultado obtido em uma frase.'],
      ['Varejo', 'Nome do cliente', 'Placeholder editável: resultado obtido em uma frase.'],
    ],
  },
  contato: {
    eyebrow: 'Contato',
    title: 'Fale com um especialista',
    lead: 'Responderemos em até um dia útil.',
    fields: {
      nome: 'Nome completo',
      nomePh: 'Seu nome',
      empresa: 'Empresa',
      empresaPh: 'Razão social',
      cargo: 'Cargo',
      cargoPh: 'Sua função',
      email: 'E-mail corporativo',
      emailPh: 'nome@empresa.com.br',
      telefone: 'Telefone',
      telefonePh: '(00) 00000-0000',
      segmento: 'Segmento',
      mensagem: 'Mensagem',
      mensagemPh: 'Conte em poucas linhas o que você precisa resolver.',
    },
    segments: ['Banco', 'Fintech', 'Subadquirente', 'Outro'],
    submit: 'Enviar mensagem',
    sending: 'Enviando…',
    schedule: 'Agendar uma conversa →',
    sent: 'Mensagem registrada. Nosso time responde em até um dia útil.',
    salesTitle: 'Comercial',
    hours: 'Atendimento de segunda a sexta, das 9h às 18h.',
    addressTitle: 'Endereço',
    address: ['Av. Placeholder, 1000 · 10º andar', 'São Paulo, SP · 00000-000'],
    socialTitle: 'Redes',
  },
};

const en: typeof pt = {
  produtos: {
    eyebrow: 'Products and solutions',
    title: 'One infrastructure, every financial solution your business needs',
    lead: 'From core banking to acquiring, each layer works on its own or integrated. You choose where to start.',
    ctaTitle: 'Not sure where to start?',
    ctaText:
      'Our team designs the technical plan together with yours, starting from what already exists in your operation.',
  },
  bancos: {
    eyebrow: 'Solutions · For banks',
    title: 'Banks that evolve without starting over',
    lead: "Connect new products to the core you already have, at the pace of your roadmap and under the regulator's rules.",
    contextEyebrow: 'Market context',
    contextTitle: 'The pressure comes from outside, but the bottleneck is internal',
    context: [
      ['New entrants, same licences', 'Fintechs launch in weeks what takes quarters inside a bank.'],
      ['Legacy that is hard to touch', 'Every change to the core carries high operational risk.'],
      ['Growing regulatory demand', 'Reporting and controls consume the technology team.'],
    ],
    beforeTitle: "Before and after, inside the bank's operation",
    todayTitle: 'Today',
    today: [
      'Product projects stuck in the core queue',
      'Reconciliation in spreadsheets across vendors',
      'Every new rail requires its own project',
    ],
    withTitle: 'With Corebanx',
    with: [
      'New products shipped on top of the current core',
      'Automatic reconciliation in a single statement',
      'New rails enabled by configuration',
    ],
    useCasesEyebrow: 'Use cases',
    useCasesTitle: 'Where banks start',
    tabs: [
      {
        label: 'White label digital account',
        title: 'White label digital account',
        text: "Launch a complete account under the bank's brand without touching the legacy system.",
        checks: [
          'Digital onboarding with biometrics',
          'iOS and Android apps published under your brand',
          'PIX, card and boleto from day one',
        ],
      },
      {
        label: 'Own acquiring',
        title: 'Own acquiring',
        text: 'Capture and settle transactions from your own merchant portfolio.',
        checks: [
          'Terminals and gateway under your brand',
          'Configurable split and advance payment',
          'Acquiring revenue kept in house',
        ],
      },
      {
        label: 'Rail modernisation',
        title: 'Rail modernisation',
        text: 'Replace point-to-point integrations with a single messaging layer.',
        checks: [
          'Standardised ISO 20022 messaging',
          'Automatic reconciliation and reprocessing',
          'End-to-end transaction observability',
        ],
      },
    ],
    volumeLabel: 'CAPTURED VOLUME',
    isoMessages: [
      'pacs.008 · credit transfer',
      'pacs.002 · status report',
      'camt.054 · notification',
      'camt.053 · statement',
    ],
    trustTitle: 'Why regulated institutions choose Corebanx',
    trust: [
      ['Regulatory', 'Processes and reporting designed for the supervised environment.'],
      ['Security', 'Encryption, biometrics and audit trails by default.'],
      ['Scale', '16.7K proven TPS and 99.99% uptime in the SLA.'],
      ['Support', 'Dedicated technical team from integration to go-live.'],
    ],
    proofTitle: 'Financial institutions operating with Corebanx',
    proofLogo: 'institution logo',
    ctaTitle: 'Talk to our team about your operation',
    ctaText: 'We bring a specialist who has already deployed infrastructure in regulated institutions.',
  },
  quemSomos: {
    eyebrow: 'About us',
    title: 'An infratech built by people who run financial systems',
    lead: 'We exist to solve what blocks innovation inside institutions: the infrastructure.',
    timelineEyebrow: 'Timeline',
    timeline: [
      ['2021', 'Founded', 'Corebanx starts with a focus on core banking as a service.'],
      ['2022', 'First integrations', 'Digital account and PIX in production with early partners.'],
      ['2023', 'Payments layer', 'Rails unified and payment split launched.'],
      ['2024', 'Acquiring and white label', "Full platform available under the partner's brand."],
      ['2025', 'Proven scale', '16.7K TPS and ISO 20022 messaging in operation.'],
    ],
    missionEyebrow: 'Mission',
    missionTitle: 'Make financial infrastructure a solved detail for those who want to innovate.',
    values: [
      ['Solidity', 'Staying up is the baseline, not the differentiator.'],
      ['Clarity', 'Documentation and contracts without fine print.'],
      ['Partnership', "Our team joins the client's project."],
      ['Rigour', 'Security and regulation before any shortcut.'],
    ],
    partnersEyebrow: 'Strategic partners',
    partnerLogo: 'partner logo',
    closingTitle: 'Explore the platform or talk to our team.',
  },
  cases: {
    eyebrow: 'Cases and partners',
    title: 'Results built together with our partners',
    logo: 'logo',
    cards: [
      ['Bank', 'Client name', 'Editable placeholder: the result achieved, in one sentence.'],
      ['Fintech', 'Client name', 'Editable placeholder: the result achieved, in one sentence.'],
      ['Sub-acquirer', 'Client name', 'Editable placeholder: the result achieved, in one sentence.'],
      ['Retail', 'Client name', 'Editable placeholder: the result achieved, in one sentence.'],
    ],
  },
  contato: {
    eyebrow: 'Contact',
    title: 'Talk to a specialist',
    lead: 'We reply within one business day.',
    fields: {
      nome: 'Full name',
      nomePh: 'Your name',
      empresa: 'Company',
      empresaPh: 'Legal name',
      cargo: 'Role',
      cargoPh: 'Your function',
      email: 'Work email',
      emailPh: 'name@company.com',
      telefone: 'Phone',
      telefonePh: '(00) 00000-0000',
      segmento: 'Segment',
      mensagem: 'Message',
      mensagemPh: 'Tell us in a few lines what you need to solve.',
    },
    segments: ['Bank', 'Fintech', 'Sub-acquirer', 'Other'],
    submit: 'Send message',
    sending: 'Sending…',
    schedule: 'Schedule a call →',
    sent: 'Message recorded. Our team replies within one business day.',
    salesTitle: 'Sales',
    hours: 'Available Monday to Friday, 9am to 6pm.',
    addressTitle: 'Address',
    address: ['Av. Placeholder, 1000 · 10th floor', 'São Paulo, SP · 00000-000'],
    socialTitle: 'Social',
  },
};

const es: typeof pt = {
  produtos: {
    eyebrow: 'Productos y soluciones',
    title: 'Una infraestructura, todas las soluciones financieras que tu negocio necesita',
    lead: 'Del core bancario a la adquirencia, cada capa funciona aislada o integrada. Tú eliges por dónde empezar.',
    ctaTitle: '¿No sabes por dónde empezar?',
    ctaText:
      'Nuestro equipo diseña el plan técnico junto al tuyo, a partir de lo que ya existe en tu operación.',
  },
  bancos: {
    eyebrow: 'Soluciones · Para bancos',
    title: 'Bancos que evolucionan sin empezar de cero',
    lead: 'Conecta nuevos productos al core que ya existe, al ritmo de tu roadmap y bajo las reglas del regulador.',
    contextEyebrow: 'Contexto de mercado',
    contextTitle: 'La presión viene de afuera, pero el cuello de botella es interno',
    context: [
      [
        'Nuevos entrantes, las mismas licencias',
        'Las fintechs lanzan en semanas lo que en el banco toma trimestres.',
      ],
      ['Legado difícil de tocar', 'Cada cambio en el core carga un alto riesgo operativo.'],
      ['Exigencia regulatoria creciente', 'Reportes y controles consumen al equipo de tecnología.'],
    ],
    beforeTitle: 'Antes y después, en la operación del banco',
    todayTitle: 'Hoy',
    today: [
      'Proyectos de producto detenidos en la fila del core',
      'Conciliación en hojas de cálculo entre proveedores',
      'Cada nuevo riel exige un proyecto propio',
    ],
    withTitle: 'Con Corebanx',
    with: [
      'Nuevos productos publicados sobre el core actual',
      'Conciliación automática en un solo estado de cuenta',
      'Rieles nuevos activados por configuración',
    ],
    useCasesEyebrow: 'Casos de uso',
    useCasesTitle: 'Por dónde empiezan los bancos',
    tabs: [
      {
        label: 'Cuenta digital white label',
        title: 'Cuenta digital white label',
        text: 'Lanza una cuenta completa con la marca del banco, sin tocar el sistema legado.',
        checks: [
          'Onboarding digital con biometría',
          'Apps iOS y Android publicadas bajo tu marca',
          'PIX, tarjeta y boleto desde el primer día',
        ],
      },
      {
        label: 'Adquirencia propia',
        title: 'Adquirencia propia',
        text: 'Captura y liquida transacciones de tu propio portafolio de comercios.',
        checks: [
          'Terminales y gateway bajo tu marca',
          'Split y adelanto configurables',
          'Ingresos de adquirencia dentro de casa',
        ],
      },
      {
        label: 'Modernización de rieles',
        title: 'Modernización de rieles',
        text: 'Cambia integraciones punto a punto por una sola capa de mensajería.',
        checks: [
          'Mensajería ISO 20022 estandarizada',
          'Conciliación y reprocesamiento automáticos',
          'Observabilidad de las transacciones de punta a punta',
        ],
      },
    ],
    volumeLabel: 'VOLUMEN CAPTURADO',
    isoMessages: [
      'pacs.008 · credit transfer',
      'pacs.002 · status report',
      'camt.054 · notification',
      'camt.053 · statement',
    ],
    trustTitle: 'Por qué las instituciones reguladas eligen Corebanx',
    trust: [
      ['Regulatorio', 'Procesos y reportes diseñados para el entorno supervisado.'],
      ['Seguridad', 'Cifrado, biometría y trazas de auditoría por defecto.'],
      ['Escala', '16,7K TPS comprobados y uptime de 99,99% en SLA.'],
      ['Soporte', 'Equipo técnico dedicado desde la integración hasta el go-live.'],
    ],
    proofTitle: 'Instituciones financieras que operan con Corebanx',
    proofLogo: 'logo de la institución',
    ctaTitle: 'Habla con nuestro equipo sobre tu operación',
    ctaText:
      'Traemos a un especialista que ya implementó infraestructura en instituciones reguladas.',
  },
  quemSomos: {
    eyebrow: 'Quiénes somos',
    title: 'Una infratech construida por quienes operan sistemas financieros',
    lead: 'Nacimos para resolver lo que traba la innovación dentro de las instituciones: la infraestructura.',
    timelineEyebrow: 'Línea de tiempo',
    timeline: [
      ['2021', 'Fundación', 'Corebanx nace con foco en core bancario como servicio.'],
      [
        '2022',
        'Primeras integraciones',
        'Cuenta digital y PIX en producción con los primeros socios.',
      ],
      ['2023', 'Capa de pagos', 'Unificación de los rieles y lanzamiento del split de pago.'],
      [
        '2024',
        'Adquirencia y white label',
        'Plataforma completa disponible bajo la marca del socio.',
      ],
      ['2025', 'Escala comprobada', '16,7K TPS y mensajería ISO 20022 en operación.'],
    ],
    missionEyebrow: 'Misión',
    missionTitle:
      'Convertir la infraestructura financiera en un detalle resuelto para quien quiere innovar.',
    values: [
      ['Solidez', 'Que el sistema esté en el aire es lo mínimo, no el diferencial.'],
      ['Claridad', 'Documentación y contratos sin letra chica.'],
      ['Alianza', 'Nuestro equipo entra junto al proyecto del cliente.'],
      ['Rigor', 'Seguridad y regulación antes que cualquier atajo.'],
    ],
    partnersEyebrow: 'Socios estratégicos',
    partnerLogo: 'logo del socio',
    closingTitle: 'Conoce la plataforma o habla con nuestro equipo.',
  },
  cases: {
    eyebrow: 'Casos y socios',
    title: 'Resultados construidos junto a nuestros socios',
    logo: 'logo',
    cards: [
      ['Banco', 'Nombre del cliente', 'Placeholder editable: el resultado obtenido en una frase.'],
      ['Fintech', 'Nombre del cliente', 'Placeholder editable: el resultado obtenido en una frase.'],
      [
        'Subadquirente',
        'Nombre del cliente',
        'Placeholder editable: el resultado obtenido en una frase.',
      ],
      ['Retail', 'Nombre del cliente', 'Placeholder editable: el resultado obtenido en una frase.'],
    ],
  },
  contato: {
    eyebrow: 'Contacto',
    title: 'Habla con un especialista',
    lead: 'Respondemos en un día hábil.',
    fields: {
      nome: 'Nombre completo',
      nomePh: 'Tu nombre',
      empresa: 'Empresa',
      empresaPh: 'Razón social',
      cargo: 'Cargo',
      cargoPh: 'Tu función',
      email: 'Correo corporativo',
      emailPh: 'nombre@empresa.com',
      telefone: 'Teléfono',
      telefonePh: '(00) 00000-0000',
      segmento: 'Segmento',
      mensagem: 'Mensaje',
      mensagemPh: 'Cuéntanos en pocas líneas qué necesitas resolver.',
    },
    segments: ['Banco', 'Fintech', 'Subadquirente', 'Otro'],
    submit: 'Enviar mensaje',
    sending: 'Enviando…',
    schedule: 'Agendar una conversación →',
    sent: 'Mensaje registrado. Nuestro equipo responde en un día hábil.',
    salesTitle: 'Comercial',
    hours: 'Atención de lunes a viernes, de 9 a 18 h.',
    addressTitle: 'Dirección',
    address: ['Av. Placeholder, 1000 · piso 10', 'São Paulo, SP · 00000-000'],
    socialTitle: 'Redes',
  },
};

export const pages = { pt, en, es };
